---
title: "Working with MS/MS data in XCMS3"
author: "Michael Witting"
date: "8 Juni 2018"
output:
  ioslides_presentation: default
  beamer_presentation: default
  slidy_presentation: default
  widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Working with MS/MS

- DDA & DIA MS/MS is data is covered
- How to link MS1 peaks with DDA MS/MS data?
- How to reconstruct MS/MS spectrum from DIA data

## Dataset Description

- Agilent Pesticide Mix
- Collected on a AB Sciex TripleToF 6600
- RP separation on a Waters BEH C18 column
- DDA & DIA was collected

## Prepare data

```{r load data, echo=TRUE}
#load required libraries
library(xcms)

#load data
xrms <- readMSData("data\\PestMix1_DDA.mzML", mode = "onDisk", centroided = TRUE)

#plot BPC
bpis <- chromatogram(xrms, aggregationFun = "max")
plot(bpis)


```

## Plot a BPC

```{r BPC plot}
plot(bpis)
```

## Make an EIC

```{r, echo=TRUE}
#Fluopicolide, exact mass = 381.965430576, [M+H]+ = 382.972706
eic <- chromatogram(xrms, aggregationFun = "max", mz = c(382.96, 382.98))
plot(eic)
```

## Extract MS2 spectra from DDA

```{r, echo=TRUE}
#get all MS2 spectra from DDA experiment
ms2spectra <- spectra(filterMsLevel(xrms, msLevel = 2))
ms2spectrum <- ms2spectra[[1]]
ms2spectrum@precursorMz
```

